### ISSUE TITLE
[Bug] Some options do not support Chinese.

### ISSUE THREAD

**Issue by QianFuv** [KostromDan/Crash-Assistant#2]
![image](https://github.com/user-attachments/assets/0c08c0b5-1ffd-4d5e-a8e0-9e8c9b28f1aa)

**Comment by KostromDan** [comment]
1.1.1 with fix avalible on Cuseforge and Modrinth

**Comment by QianFuv** [comment]
Thank you for such a quick fix! I've been updating and testing it for the first time. The issue has now been fixed!
